import type { HermesCapabilityDefinition } from "./control-center-types";

type Entry = Omit<HermesCapabilityDefinition, "keywords"> & { keywords?: string[] };

function capability(entry: Entry): HermesCapabilityDefinition {
  return { ...entry, keywords: entry.keywords ?? [] };
}

const installedEvidence = "Installed Hermes Desktop route and source audit";
const liveEvidence = "Installed Hermes management contract and live response";

export const HERMES_CAPABILITY_REGISTRY: readonly HermesCapabilityDefinition[] = [
  capability({ id: "chat", name: "Chat and sessions", group: "Sessions", audience: "operator", desktopSource: "/ and apps/desktop/src/app/chat", installedVersionSupport: "Supported", installedSupported: true, interface: "Gateway WebSocket sessions and /api/sessions", cabinetSurface: "Agents conversations", cabinetHref: "/agents", parityState: "mapped", readWriteRisk: "consequential", mode: "Operator", missingWork: "Keep Hermes transcript and execution history canonical.", testEvidence: installedEvidence, keywords: ["conversation", "chat", "history"] }),
  capability({ id: "command-center", name: "Command Center", group: "Overview", audience: "operator", desktopSource: "/command-center", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/status, /api/system/stats, /api/ops/*", cabinetSurface: "Hermes Overview", cabinetHref: "/hermes", parityState: "visible_read_only", readWriteRisk: "low", mode: "Operator", missingWork: "Add confirmed maintenance actions after owner review.", testEvidence: installedEvidence }),
  capability({ id: "skills", name: "Skills", group: "Tools", audience: "operator", desktopSource: "/skills", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/skills and /api/skills/hub/*", cabinetSurface: "Cabinet Skills and Hermes Tools", cabinetHref: "/hermes?section=tools", parityState: "mapped", readWriteRisk: "consequential", mode: "Operator", missingWork: "No duplicate catalog. Continue projecting Hermes skill provenance and enablement.", testEvidence: liveEvidence }),
  capability({ id: "messaging", name: "Messaging", group: "Messaging", audience: "operator", desktopSource: "/messaging", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/messaging/platforms and Gateway", cabinetSurface: "Hermes Messaging", cabinetHref: "/hermes?section=messaging", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add confirmed platform repair and test actions without exposing credentials.", testEvidence: liveEvidence }),
  capability({ id: "artifacts", name: "Artifacts", group: "Artifacts", audience: "operator", desktopSource: "/artifacts", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/sessions/{id}/messages, /api/files, runtime tool events", cabinetSurface: "Hermes Artifacts", cabinetHref: "/hermes?section=artifacts", parityState: "visible_read_only", readWriteRisk: "low", mode: "Operator", missingWork: "Add safe preview, reveal, and download controls while preserving session and run association.", testEvidence: "Exact artifact projection contract plus installed Hermes /api/files response" }),
  capability({ id: "cron", name: "Cron and background jobs", group: "Automations", audience: "operator", desktopSource: "/cron", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/cron/jobs and /api/cron/jobs/{id}/runs", cabinetSurface: "Hermes Automations", cabinetHref: "/hermes?section=automations", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add a reviewed management surface; existing mutations remain confirmation and idempotency gated.", testEvidence: liveEvidence }),
  capability({ id: "profiles", name: "Profiles", group: "Agents", audience: "management", desktopSource: "/profiles", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/profiles and /api/profiles/{name}/soul", cabinetSurface: "Hermes Agents", cabinetHref: "/hermes?section=agents", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add reviewed profile management and keep profile and runtime agent identities visually distinct.", testEvidence: liveEvidence }),
  capability({ id: "agents-subagents", name: "Agents and subagents", group: "Agents", audience: "operator", desktopSource: "/agents", installedVersionSupport: "Supported", installedSupported: true, interface: "Gateway events, run state, kanban worker API when plugin is enabled", cabinetSurface: "Hermes Agents", cabinetHref: "/hermes?section=agents", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Normalize current tool, parent session, result, error, and supported stop controls.", testEvidence: installedEvidence }),
  capability({ id: "starmap", name: "Starmap and memory graph", group: "Memory", audience: "operator", desktopSource: "/starmap", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/learning/graph and /api/learning/node", cabinetSurface: "Hermes Memory", cabinetHref: "/hermes?section=memory", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Render only reported nodes and recall relationships. No fabricated edges.", testEvidence: liveEvidence }),
  capability({ id: "settings", name: "Settings", group: "Settings", audience: "management", desktopSource: "/settings", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/config/schema, /api/config and scoped management APIs", cabinetSurface: "Hermes Settings", cabinetHref: "/hermes?section=settings", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Expose safe typed fields gradually; raw config remains Developer-only.", testEvidence: liveEvidence }),

  capability({ id: "providers", name: "Providers", group: "Providers and models", audience: "management", desktopSource: "/settings?tab=providers", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/auth/providers, /api/providers/oauth, /api/providers/validate", cabinetSurface: "Hermes Settings", cabinetHref: "/hermes?section=settings", parityState: "visible_read_only", readWriteRisk: "secret", mode: "Operator", missingWork: "Add safe OAuth/setup flows; never serialize tokens.", testEvidence: liveEvidence }),
  capability({ id: "provider-accounts", name: "Provider accounts", group: "Providers and models", audience: "management", desktopSource: "/settings?tab=providers&pview=accounts", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/providers/oauth and /api/credentials/pool", cabinetSurface: "Hermes Settings", cabinetHref: "/hermes?section=settings", parityState: "visible_read_only", readWriteRisk: "secret", mode: "Operator", missingWork: "Expose account labels and health only.", testEvidence: liveEvidence }),
  capability({ id: "models", name: "Models", group: "Providers and models", audience: "management", desktopSource: "/settings?tab=config:model", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/model/info, /api/model/options, /api/model/set", cabinetSurface: "Hermes Settings", cabinetHref: "/hermes?section=settings", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add confirmed default and profile override controls.", testEvidence: liveEvidence }),
  capability({ id: "api-keys-tools", name: "API keys and tools", group: "Tools", audience: "management", desktopSource: "/settings?tab=keys", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/env, /api/tools/toolsets", cabinetSurface: "Hermes Tools", cabinetHref: "/hermes?section=tools", parityState: "visible_read_only", readWriteRisk: "secret", mode: "Operator", missingWork: "Show configured/not configured only. Values stay server-side.", testEvidence: liveEvidence }),
  capability({ id: "gateway", name: "Gateway", group: "Runtime", audience: "management", desktopSource: "/settings?tab=gateway", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/gateway/start|stop|restart and detailed health", cabinetSurface: "Hermes Overview", cabinetHref: "/hermes?capability=gateway", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add confirmed restart/reconnect with failure-log excerpt.", testEvidence: liveEvidence }),
  capability({ id: "mcp", name: "MCP", group: "Tools", audience: "management", desktopSource: "/skills?tab=mcp", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/mcp/servers and /api/mcp/catalog", cabinetSurface: "Hermes Tools", cabinetHref: "/hermes?section=tools", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add a reviewed management surface; mutations remain confirmation gated.", testEvidence: liveEvidence }),
  capability({ id: "plugins", name: "Plugins", group: "Tools", audience: "management", desktopSource: "/settings?tab=plugins", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/dashboard/plugins and /api/dashboard/agent-plugins/*", cabinetSurface: "Hermes Tools", cabinetHref: "/hermes?section=tools", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add explicit install/update/disable confirmations.", testEvidence: liveEvidence }),
  capability({ id: "notifications", name: "Notifications", group: "Settings", audience: "management", desktopSource: "/settings?tab=notifications", installedVersionSupport: "Supported", installedSupported: true, interface: "Cabinet notification event settings plus browser permission state", cabinetSurface: "Hermes Settings", cabinetHref: "/hermes?section=settings", parityState: "mapped", readWriteRisk: "low", mode: "Operator", missingWork: "Browser/OS delivery remains subject to browser permission; Cabinet does not claim to edit Hermes Desktop local preferences.", testEvidence: "Cabinet notification settings and in-app test notification" }),
  capability({ id: "archived-chats", name: "Archived chats", group: "Sessions", audience: "operator", desktopSource: "/settings?tab=sessions", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/sessions, search, export, delete", cabinetSurface: "Hermes Sessions", cabinetHref: "/hermes?section=sessions", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add restore/export and separately confirmed delete.", testEvidence: liveEvidence }),
  capability({ id: "billing", name: "Billing", group: "Providers and models", audience: "management", desktopSource: "Upstream /settings billing module", installedVersionSupport: "Not detected in the installed Desktop build", installedSupported: false, interface: "Upstream-only portal billing client", cabinetSurface: "Hermes Settings", cabinetHref: "/hermes?section=settings", parityState: "unsupported", readWriteRisk: "consequential", mode: "Operator", missingWork: "Upgrade installed Desktop/backend only after separate approval and re-audit.", testEvidence: "Present in explicit upstream audit and absent from the installed Desktop interface" }),
  capability({ id: "about-updates", name: "About and updates", group: "Runtime", audience: "management", desktopSource: "/settings?tab=about", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/hermes/update/check and app metadata", cabinetSurface: "Hermes Overview", cabinetHref: "/hermes?capability=about-updates", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Upgrade requires explicit owner approval and restart handoff.", testEvidence: liveEvidence }),
  capability({ id: "model-settings", name: "Model settings", group: "Settings", audience: "management", desktopSource: "/settings?tab=config:model", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/model/* and config schema", cabinetSurface: "Hermes Settings", cabinetHref: "/hermes?section=settings", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add reasoned, confirmed mutations.", testEvidence: liveEvidence }),
  capability({ id: "chat-settings", name: "Chat settings", group: "Settings", audience: "management", desktopSource: "/settings?tab=config:chat", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/config/schema and /api/config", cabinetSurface: "Hermes Settings", cabinetHref: "/hermes?section=settings", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Project safe fields into typed controls.", testEvidence: liveEvidence }),
  capability({ id: "appearance", name: "Appearance", group: "Settings", audience: "management", desktopSource: "/settings?tab=config:appearance", installedVersionSupport: "Desktop-local", installedSupported: true, interface: "Desktop local theme and font preferences", cabinetSurface: "Cabinet appearance", cabinetHref: "/settings/appearance", parityState: "mapped", readWriteRisk: "low", mode: "Operator", missingWork: "Desktop-only themes remain diagnostic because Cabinet has its own theme system.", testEvidence: installedEvidence }),
  capability({ id: "workspace", name: "Workspace", group: "Settings", audience: "management", desktopSource: "/settings?tab=config:workspace", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/config and /api/fs/default-cwd", cabinetSurface: "Cabinet rooms and linked repos", cabinetHref: "/", parityState: "mapped", readWriteRisk: "consequential", mode: "Operator", missingWork: "Keep Hermes working directory visible without duplicating Cabinet workspace state.", testEvidence: liveEvidence }),
  capability({ id: "safety", name: "Safety", group: "Settings", audience: "management", desktopSource: "/settings?tab=config:safety", installedVersionSupport: "Supported", installedSupported: true, interface: "Approvals config, hooks, security audit", cabinetSurface: "Existing Hermes approval boundaries", cabinetHref: "/hermes?section=settings", parityState: "mapped", readWriteRisk: "consequential", mode: "Operator", missingWork: "Do not weaken Jeremy-only approval gates.", testEvidence: liveEvidence }),
  capability({ id: "memory-context", name: "Memory and context", group: "Memory", audience: "management", desktopSource: "/settings?tab=config:memory", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/memory and /api/memory/providers/*", cabinetSurface: "Hermes Memory", cabinetHref: "/hermes?section=memory", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add safe inspect/search; delete/archive only when supported and confirmed.", testEvidence: liveEvidence }),
  capability({ id: "voice", name: "Voice", group: "Settings", audience: "operator", desktopSource: "Chat composer and /settings voice fields", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/audio/transcribe, /api/audio/speak, browser permission status", cabinetSurface: "Hermes Settings", cabinetHref: "/hermes?section=settings", parityState: "visible_read_only", readWriteRisk: "low", mode: "Operator", missingWork: "Owner must grant microphone permission before recording acceptance; voice input never executes consequential work automatically.", testEvidence: "Exact audio interface contract and non-prompting browser permission probe" }),
  capability({ id: "advanced-config", name: "Advanced configuration", group: "Developer", audience: "developer", desktopSource: "/settings?tab=config:*", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/config/raw and /api/config/schema", cabinetSurface: "Hermes Developer", cabinetHref: "/hermes?mode=developer", parityState: "diagnostic_only", readWriteRisk: "secret", mode: "Developer", missingWork: "Provide redacted read-only projection before any raw editor.", testEvidence: liveEvidence }),

  capability({ id: "files", name: "Files", group: "Developer", audience: "developer", desktopSource: "Right sidebar Files", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/fs/* and /api/files/*", cabinetSurface: "Cabinet data tree and viewers", cabinetHref: "/", parityState: "mapped", readWriteRisk: "consequential", mode: "Developer", missingWork: "Hermes remote files need association and safe reveal/download.", testEvidence: liveEvidence }),
  capability({ id: "terminal", name: "Terminal", group: "Developer", audience: "developer", desktopSource: "Right sidebar Terminal", installedVersionSupport: "Supported", installedSupported: true, interface: "Hermes PTY plus Cabinet daemon PTY", cabinetSurface: "Cabinet Terminal", cabinetHref: "/hermes?mode=developer", parityState: "mapped", readWriteRisk: "consequential", mode: "Developer", missingWork: "No silent fallback between Hermes and Cabinet execution.", testEvidence: installedEvidence }),
  capability({ id: "source-review", name: "Source-control review", group: "Developer", audience: "developer", desktopSource: "Right sidebar Review", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/git/review/*", cabinetSurface: "Cabinet git history and diffs", cabinetHref: "/hermes?mode=developer", parityState: "mapped", readWriteRisk: "consequential", mode: "Developer", missingWork: "Ship/push actions remain outside read-only Control Center.", testEvidence: liveEvidence }),
  capability({ id: "projects", name: "Projects", group: "Developer", audience: "developer", desktopSource: "Chat sidebar Projects", installedVersionSupport: "Supported", installedSupported: true, interface: "Hermes project config and session cwd", cabinetSurface: "Cabinet rooms and linked repos", cabinetHref: "/", parityState: "mapped", readWriteRisk: "consequential", mode: "Developer", missingWork: "Show Hermes project identity alongside Cabinet scope.", testEvidence: installedEvidence }),
  capability({ id: "worktrees", name: "Worktrees", group: "Developer", audience: "developer", desktopSource: "Project and session controls", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/git/worktrees", cabinetSurface: "Hermes Developer", cabinetHref: "/hermes?mode=developer", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Developer", missingWork: "Add confirmed add/remove only after read-only inventory proves safe paths.", testEvidence: liveEvidence }),
  capability({ id: "session-tabs", name: "Session tabs", group: "Developer", audience: "developer", desktopSource: "Pane shell and session switcher", installedVersionSupport: "Desktop-local", installedSupported: true, interface: "Desktop pane store and Hermes session routes", cabinetSurface: "Cabinet task tabs and rail", cabinetHref: "/tasks", parityState: "mapped", readWriteRisk: "low", mode: "Developer", missingWork: "Do not duplicate desktop pane layout state.", testEvidence: installedEvidence }),
  capability({ id: "session-pinning", name: "Session pinning", group: "Sessions", audience: "operator", desktopSource: "Session sidebar actions", installedVersionSupport: "Supported", installedSupported: true, interface: "Session metadata and Desktop ordering", cabinetSurface: "Hermes Sessions", cabinetHref: "/hermes?section=sessions", parityState: "visible_read_only", readWriteRisk: "low", mode: "Operator", missingWork: "Stable remote pin mutation is not exposed by installed management API.", testEvidence: installedEvidence }),
  capability({ id: "command-palette", name: "Command palette", group: "Developer", audience: "developer", desktopSource: "Desktop command palette", installedVersionSupport: "Desktop-local", installedSupported: true, interface: "Desktop local contribution registry", cabinetSurface: "Cabinet command search", cabinetHref: "/", parityState: "mapped", readWriteRisk: "low", mode: "Developer", missingWork: "Hermes actions are discoverable through Control Center search.", testEvidence: installedEvidence }),
  capability({ id: "keyboard-shortcuts", name: "Keyboard shortcuts", group: "Developer", audience: "developer", desktopSource: "Desktop keybind panel", installedVersionSupport: "Desktop-local", installedSupported: true, interface: "Desktop local keybind store", cabinetSurface: "Cabinet keyboard shortcuts", cabinetHref: "/help", parityState: "mapped", readWriteRisk: "low", mode: "Developer", missingWork: "List Hermes-only keybindings diagnostically when safe source is available.", testEvidence: installedEvidence }),
  capability({ id: "layout-controls", name: "Layout controls", group: "Developer", audience: "developer", desktopSource: "Pane shell layouts", installedVersionSupport: "Desktop-local", installedSupported: true, interface: "Desktop local pane store", cabinetSurface: "Cabinet layout controls", cabinetHref: "/hermes?mode=developer", parityState: "mapped", readWriteRisk: "low", mode: "Developer", missingWork: "No cross-application layout synchronization.", testEvidence: installedEvidence }),
  capability({ id: "approvals", name: "Approvals and pending input", group: "Sessions", audience: "operator", desktopSource: "Chat tool approvals", installedVersionSupport: "Supported", installedSupported: true, interface: "Gateway decision events and run approval endpoint", cabinetSurface: "Cabinet Hermes conversations", cabinetHref: "/agents", parityState: "first_class", readWriteRisk: "consequential", mode: "Operator", missingWork: "Existing confirmation, owner identity, and idempotency behavior is unchanged.", testEvidence: "Cabinet Hermes gateway and run contract tests" }),
  capability({ id: "browser-opencli", name: "Browser and OpenCLI", group: "Tools", audience: "operator", desktopSource: "Hermes Terminal toolset", installedVersionSupport: "External OpenCLI installation detected at runtime", installedSupported: true, interface: "opencli doctor and browser bridge CLI", cabinetSurface: "Hermes Tools", cabinetHref: "/hermes?capability=browser-opencli", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add reviewed repair/reconnect only when the installed CLI reports a safe supported action.", testEvidence: "OpenCLI doctor plus local read-only acceptance" }),
  capability({ id: "executor", name: "Executor", group: "Tools", audience: "operator", desktopSource: "Hermes terminal/code execution", installedVersionSupport: "Supported", installedSupported: true, interface: "Toolsets, runtime tool events, terminal backend", cabinetSurface: "Hermes Tools", cabinetHref: "/hermes?section=tools", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Show backend and active action without creating a second executor.", testEvidence: liveEvidence }),
  capability({ id: "raw-logs", name: "Raw logs", group: "Developer", audience: "developer", desktopSource: "Command Center maintenance", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/logs", cabinetSurface: "Hermes Developer", cabinetHref: "/hermes?mode=developer", parityState: "diagnostic_only", readWriteRisk: "secret", mode: "Developer", missingWork: "Redact secrets and bound log output before browser exposure.", testEvidence: liveEvidence }),
  capability({ id: "gateway-diagnostics", name: "Low-level gateway diagnostics", group: "Developer", audience: "developer", desktopSource: "Gateway settings and logs", installedVersionSupport: "Supported", installedSupported: true, interface: "Gateway health, logs, drain, restart", cabinetSurface: "Hermes Developer", cabinetHref: "/hermes?mode=developer", parityState: "diagnostic_only", readWriteRisk: "secret", mode: "Developer", missingWork: "Display URL identity without query tokens or authorization material.", testEvidence: liveEvidence }),
  capability({ id: "computer-use", name: "Computer Use", group: "Tools", audience: "management", desktopSource: "/settings computer-use panel", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/tools/computer-use/status", cabinetSurface: "Hermes Tools", cabinetHref: "/hermes?section=tools", parityState: "visible_read_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Permission grants remain explicit OS-scoped actions.", testEvidence: liveEvidence }),
  capability({ id: "backups", name: "Backup and restore", group: "Settings", audience: "management", desktopSource: "Command Center maintenance", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/ops/backup and /api/ops/import", cabinetSurface: "Hermes Settings", cabinetHref: "/hermes?section=settings", parityState: "diagnostic_only", readWriteRisk: "consequential", mode: "Operator", missingWork: "Add reviewed download/import workflow with confirmation.", testEvidence: liveEvidence }),
  capability({ id: "security-audit", name: "Security audit", group: "Settings", audience: "management", desktopSource: "Command Center maintenance", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/ops/security-audit", cabinetSurface: "Hermes Settings", cabinetHref: "/hermes?section=settings", parityState: "visible_read_only", readWriteRisk: "low", mode: "Operator", missingWork: "Show bounded audit results without package credentials.", testEvidence: liveEvidence }),
  capability({ id: "usage-insights", name: "Usage insights", group: "Providers and models", audience: "management", desktopSource: "Command Center analytics", installedVersionSupport: "Supported", installedSupported: true, interface: "/api/analytics/usage and /api/analytics/models", cabinetSurface: "Hermes Overview", cabinetHref: "/hermes", parityState: "visible_read_only", readWriteRisk: "read_only", mode: "Operator", missingWork: "Add bounded cost/rate-limit summaries when reported.", testEvidence: liveEvidence }),
] as const;
