import {
  Bot,
  Pencil,
  Crown,
  Briefcase,
  DollarSign,
  Wrench,
  Megaphone,
  Search,
  ShieldCheck,
  BarChart3,
  Palette,
  Smartphone,
  Rocket,
  Handshake,
  PenTool,
  Code,
  UserCheck,
  Scale,
  Asterisk,
  Lightbulb,
  Compass,
  Cpu,
  Feather,
  Flame,
  Heart,
  Coffee,
  Mic,
  Camera,
  Hammer,
  Target,
  Zap,
  Book,
  FlaskConical,
  Gavel,
  Globe,
  Headphones,
  Leaf,
  Music,
  Stethoscope,
  Wand2,
  Anchor,
  Atom,
  Award,
  Axe,
  Bell,
  Bike,
  Binoculars,
  Brain,
  Building2,
  Calculator,
  Calendar,
  Car,
  Castle,
  Cat,
  ChefHat,
  Church,
  Clapperboard,
  Clock,
  Cloud,
  Club,
  Cog,
  Command,
  Crosshair,
  Database,
  Diamond,
  Dog,
  Drama,
  Drum,
  Dumbbell,
  Factory,
  Film,
  Fish,
  FolderKanban,
  Footprints,
  Gamepad2,
  Gem,
  GitBranch,
  Grape,
  Guitar,
  Hand,
  HardHat,
  Infinity as InfinityIcon,
  Keyboard,
  Key,
  Landmark,
  Laptop,
  Library,
  LifeBuoy,
  Link,
  Lock,
  Magnet,
  Map,
  Medal,
  Microscope,
  Monitor,
  Moon,
  Mountain,
  Network,
  Newspaper,
  Notebook,
  Package,
  Paintbrush,
  PartyPopper,
  Phone,
  PiggyBank,
  Pizza,
  Plane,
  Puzzle,
  Radio,
  Recycle,
  Ruler,
  Salad,
  Scissors,
  ScrollText,
  Send,
  Server,
  Ship,
  ShoppingBag,
  Signature,
  Sigma,
  Snowflake,
  Sprout,
  Star,
  Sun,
  Swords,
  Telescope,
  TentTree,
  TestTube,
  Theater,
  ThumbsUp,
  Ticket,
  Timer,
  Train,
  Trees,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Unlock,
  Upload,
  Users,
  Utensils,
  Video,
  Wallet,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wine,
  type LucideIcon,
} from "lucide-react";

// Full map used by catalog lookup. Lucide keys are the icon name strings.
export const ICON_CATALOG: Record<string, LucideIcon> = {
  Bot,
  Pencil,
  Crown,
  Briefcase,
  DollarSign,
  Wrench,
  Megaphone,
  Search,
  ShieldCheck,
  BarChart3,
  Palette,
  Smartphone,
  Rocket,
  Handshake,
  PenTool,
  Code,
  UserCheck,
  Scale,
  Sparkles: Asterisk,
  Lightbulb,
  Compass,
  Cpu,
  Feather,
  Flame,
  Heart,
  Coffee,
  Mic,
  Camera,
  Hammer,
  Target,
  Zap,
  Book,
  FlaskConical,
  Gavel,
  Globe,
  Headphones,
  Leaf,
  Music,
  Stethoscope,
  Wand2,
  Anchor,
  Atom,
  Award,
  Axe,
  Bell,
  Bike,
  Binoculars,
  Brain,
  Building2,
  Calculator,
  Calendar,
  Car,
  Castle,
  Cat,
  ChefHat,
  Church,
  Clapperboard,
  Clock,
  Cloud,
  Club,
  Cog,
  Command,
  Crosshair,
  Database,
  Diamond,
  Dog,
  Drama,
  Drum,
  Dumbbell,
  Factory,
  Film,
  Fish,
  FolderKanban,
  Footprints,
  Gamepad2,
  Gem,
  GitBranch,
  Grape,
  Guitar,
  Hand,
  HardHat,
  Infinity: InfinityIcon,
  Keyboard,
  Key,
  Landmark,
  Laptop,
  Library,
  LifeBuoy,
  Link,
  Lock,
  Magnet,
  Map,
  Medal,
  Microscope,
  Monitor,
  Moon,
  Mountain,
  Network,
  Newspaper,
  Notebook,
  Package,
  Paintbrush,
  PartyPopper,
  Phone,
  PiggyBank,
  Pizza,
  Plane,
  Puzzle,
  Radio,
  Recycle,
  Ruler,
  Salad,
  Scissors,
  ScrollText,
  Send,
  Server,
  Ship,
  ShoppingBag,
  Signature,
  Sigma,
  Snowflake,
  Sprout,
  Star,
  Sun,
  Swords,
  Telescope,
  TentTree,
  TestTube,
  Theater,
  ThumbsUp,
  Ticket,
  Timer,
  Train,
  Trees,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Unlock,
  Upload,
  Users,
  Utensils,
  Video,
  Wallet,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wine,
};

// Picker subset ordered for the grid. Shows every key in ICON_CATALOG.
export const ICON_PICKER_KEYS: string[] = Object.keys(ICON_CATALOG);

// Default icon per-slug, used when an agent has no explicit iconKey set.
export const DEFAULT_ICONS_BY_SLUG: Record<string, LucideIcon> = {
  general: Bot,
  editor: Pencil,
  ceo: Crown,
  coo: Briefcase,
  cfo: DollarSign,
  cto: Wrench,
  "content-marketer": Megaphone,
  seo: Search,
  "seo-specialist": Search,
  qa: ShieldCheck,
  "qa-agent": ShieldCheck,
  sales: BarChart3,
  "sales-agent": BarChart3,
  "product-manager": Briefcase,
  "ux-designer": Palette,
  "data-analyst": BarChart3,
  "social-media": Smartphone,
  "growth-marketer": Rocket,
  "customer-success": Handshake,
  copywriter: PenTool,
  devops: Code,
  developer: Code,
  "people-ops": UserCheck,
  legal: Scale,
  researcher: Search,
};

export function getIconByKey(key: string | undefined | null): LucideIcon | null {
  if (!key) return null;
  return ICON_CATALOG[key] ?? null;
}

// Audit #041: lucide identifiers like "BarChart3", "ShieldCheck", "PenTool"
// leaked into the UI via `title=` tooltips and screen-reader labels. This
// helper turns the camelCase id into a friendly label users actually
// recognise: "Bar chart 3", "Shield check", "Pen tool". Hand-overrides for
// a handful of acronyms / awkward splits live in ICON_LABEL_OVERRIDES.
const ICON_LABEL_OVERRIDES: Record<string, string> = {
  Cpu: "CPU",
  Hdd: "HDD",
  Wifi: "Wi-Fi",
  Github: "GitHub",
  Gitlab: "GitLab",
  PenTool: "Pen tool",
  Sparkles: "Sparkles",
};

export function friendlyIconName(key: string): string {
  if (!key) return key;
  if (ICON_LABEL_OVERRIDES[key]) return ICON_LABEL_OVERRIDES[key];
  // Split camelCase / PascalCase into words; keep digit suffixes.
  const spaced = key
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2");
  // Lowercase everything except the first character.
  const lower = spaced.toLowerCase();
  return lower.charAt(0).toUpperCase() + lower.slice(1);
}

export function resolveAgentIcon(
  slug: string,
  iconKey?: string | null
): LucideIcon {
  const explicit = getIconByKey(iconKey);
  if (explicit) return explicit;
  return DEFAULT_ICONS_BY_SLUG[slug] ?? Bot;
}
